// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddPost(arg1:backend.Post):Promise<void>;

export function GetAllPosts():Promise<Array<backend.Post>>;

export function UpdatePost(arg1:backend.Post):Promise<void>;
