// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPost(arg1) {
  return window['go']['main']['App']['AddPost'](arg1);
}

export function GetAllPosts() {
  return window['go']['main']['App']['GetAllPosts']();
}
